#!/usr/bin/env python3
"""
DAK GitHub Updater - Issue Creator

Creates GitHub issues for DAK updates and assigns them to Copilot.
Usage: python create_issues.py --config config.json --updates updates.json
"""

import argparse
import json
import sys
import time
import requests


def create_issue(owner, repo, token, title, body, labels=None, assignees=None):
    """Create a single GitHub issue. Returns issue data or error dict."""
    url = f"https://api.github.com/repos/{owner}/{repo}/issues"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }
    payload = {
        "title": title,
        "body": body,
        "labels": labels or ["dak-update"],
    }

    # Try with copilot assignee first
    if assignees:
        payload["assignees"] = assignees

    resp = requests.post(url, headers=headers, json=payload)

    # If assignee failed (copilot not available), retry without
    if resp.status_code == 422 and assignees:
        payload.pop("assignees", None)
        # Add @copilot mention to body as fallback
        payload["body"] = body + "\n\n---\n_@copilot — please implement this change and open a pull request._"
        resp = requests.post(url, headers=headers, json=payload)

    if resp.status_code == 201:
        data = resp.json()
        return {
            "success": True,
            "number": data["number"],
            "url": data["html_url"],
            "title": title,
        }
    else:
        return {
            "success": False,
            "status_code": resp.status_code,
            "error": resp.text,
            "title": title,
        }


def format_issue_body(update):
    """Format a single update into a GitHub issue body."""
    body_parts = []

    # Summary
    body_parts.append(f"## Summary\n{update.get('summary', 'No summary provided.')}\n")

    # Change details
    body_parts.append(f"## Change Details\n")
    body_parts.append(f"- **File:** `{update['file']}`")
    body_parts.append(f"- **Sheet:** {update['sheet']}")
    body_parts.append(f"- **Change Type:** {update['change_type']}")
    if update.get("row_identifier"):
        body_parts.append(f"- **Row Identifier:** {update['row_identifier']}")
    body_parts.append("")

    # Diff table
    if update.get("diff"):
        body_parts.append("### Diff\n")
        body_parts.append("| Column | Current Value | New Value |")
        body_parts.append("|--------|--------------|-----------|")
        for col, values in update["diff"].items():
            old = values.get("old", "—")
            new = values.get("new", "—")
            body_parts.append(f"| {col} | {old} | {new} |")
        body_parts.append("")

    # Implementation instructions
    body_parts.append("## Implementation Instructions\n")
    if update["change_type"].lower() == "modify":
        body_parts.append(
            f"In file `{update['file']}`, sheet `{update['sheet']}`, "
            f"locate the row identified by {update.get('row_identifier', 'the criteria above')} "
            f"and apply the column changes shown in the diff table above."
        )
    elif update["change_type"].lower() == "add":
        body_parts.append(
            f"In file `{update['file']}`, sheet `{update['sheet']}`, "
            f"insert a new row with the values specified in the 'New Value' column of the diff table."
        )
    elif update["change_type"].lower() == "delete":
        body_parts.append(
            f"In file `{update['file']}`, sheet `{update['sheet']}`, "
            f"delete the row identified by {update.get('row_identifier', 'the criteria above')}."
        )
    body_parts.append("")

    # Rationale
    if update.get("rationale"):
        body_parts.append(f"## Rationale\n{update['rationale']}\n")

    # Metadata
    body_parts.append("---")
    body_parts.append("_This issue was auto-generated by the DAK GitHub Updater skill._")

    return "\n".join(body_parts)


def format_issue_title(update):
    """Generate a descriptive issue title."""
    change_type = update.get("change_type", "Update").capitalize()
    sheet = update.get("sheet", "Unknown Sheet")
    summary = update.get("summary", "")
    # Truncate summary for title
    short_summary = summary[:80] + "..." if len(summary) > 80 else summary
    return f"[DAK Update] {change_type} {sheet}: {short_summary}"


def main():
    parser = argparse.ArgumentParser(description="Create GitHub issues for DAK updates")
    parser.add_argument("--config", required=True, help="Path to config JSON (owner, repo, token)")
    parser.add_argument("--updates", required=True, help="Path to updates JSON array")
    parser.add_argument("--output", default="results.json", help="Path to save results")
    parser.add_argument("--delay", type=float, default=1.0, help="Delay between API calls (seconds)")
    parser.add_argument("--labels", nargs="*", default=["dak-update"], help="Labels to apply")
    parser.add_argument("--assign-copilot", action="store_true", default=True, help="Assign to copilot")
    args = parser.parse_args()

    with open(args.config) as f:
        config = json.load(f)

    with open(args.updates) as f:
        updates = json.load(f)

    owner = config["owner"]
    repo = config["repo"]
    token = config["token"]
    assignees = ["copilot"] if args.assign_copilot else []

    results = []
    for i, update in enumerate(updates):
        title = format_issue_title(update)
        body = format_issue_body(update)

        print(f"[{i+1}/{len(updates)}] Creating issue: {title}")
        result = create_issue(owner, repo, token, title, body, labels=args.labels, assignees=assignees)
        results.append(result)

        if result["success"]:
            print(f"  ✓ Created #{result['number']}: {result['url']}")
        else:
            print(f"  ✗ Failed ({result['status_code']}): {result['error'][:200]}")

        if i < len(updates) - 1:
            time.sleep(args.delay)

    with open(args.output, "w") as f:
        json.dump(results, f, indent=2)

    succeeded = sum(1 for r in results if r["success"])
    failed = len(results) - succeeded
    print(f"\nDone. {succeeded} created, {failed} failed. Results saved to {args.output}")


if __name__ == "__main__":
    main()
